'================================================== 
' Generated by DWRAD version 1.0.0.0
' Irhantoro E
' Trans7

' Created Date: 3/16/2008 4:19:05 PM
' 


Public Class uiMstItemCluster
    Private Const mUiName As String = "Master Item Cluster"
    Private Const SHOW_SAVE_CONFIRMATION As Boolean = True

    Private Event FormBeforeOpenRow(ByRef id As Object)
    Private Event FormAfterOpenRow(ByRef id As Object)
    Private Event FormBeforeSave(ByRef id As Object)
    Private Event FormAfterSave(ByRef id As Object, ByVal result As FormSaveResult)
    Private Event FormBeforeNew()
    Private Event FormBeforeDelete(ByRef id As Object)
    Private Event FormAfterDelete(ByRef id As Object)

    Private FILTER_QUERY_MODE As Boolean
    Private DATA_ISLOCKED As Boolean

    Private objFormError As Windows.Forms.ErrorProvider = New Windows.Forms.ErrorProvider

    Private tbl_MstItemClusterGroup As DataTable = clsDataset.CreateTblMstClusterGroup()
    Private tbl_MstItemClusterGroup_Temp As DataTable = clsDataset.CreateTblMstClusterGroup
    Private tbl_MstItemCluster As DataTable = clsDataset.CreateTblMstCluster()
    Private tbl_MstItemCluster_temp As DataTable = clsDataset.CreateTblMstCluster()
    Private tbl_MstItem As DataTable = clsDataset.CreateTblMstClusterGroup()
    Private tbl_MstItem_all As DataTable = clsDataset.CreateTblMstItem()
    Private tbl_MstItem_all_temp As DataTable = New DataTable
    Private tbl_temp As DataTable = New DataTable

#Region " Window Parameter "
    ' TODO: Buat variabel untuk menampung parameter window 

#End Region

#Region " Overrides "

    Public Overrides Function btnQuery_Click() As Boolean
        Me.PnlDfSearch.Visible = Not Me.PnlDfSearch.Visible
        If Me.PnlDfSearch.Visible Then
            FILTER_QUERY_MODE = True
            Me.tbtnQuery.CheckState = CheckState.Checked
        Else
            FILTER_QUERY_MODE = False
            Me.tbtnQuery.CheckState = CheckState.Unchecked
        End If
        Return MyBase.btnQuery_Click()
    End Function

    Public Overrides Function btnNew_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        'If Me.ftabMain.SelectedIndex = 0 Or Me.ftabMain.SelectedIndex = 2 Then
        '    Me.ftabMain.SelectedIndex = 1
        'End If
        'MsgBox("Use this feature only to create NEW GROUP or NEW CATEGORY." & vbCrLf & _
        '        "To create NEW ITEM, just insert it on detil area after selecting Group and Category.", MsgBoxStyle.Information)
        MsgBox("To create NEW ITEM, just insert it on detil area after selecting Group and Category.", MsgBoxStyle.Information)

        Me.uiMstItemCluster_NewData()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnNew_Click()
    End Function

    Public Overrides Function btnLoad_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Retrieve()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnLoad_Click()
    End Function

    Public Overrides Function btnSave_Click() As Boolean
        If Me.uiMstItemCluster_FormError() Then
            Return True
        End If
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Save()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnSave_Click()
    End Function


    Public Overrides Function btnPrint_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Print()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnPrint_Click()
    End Function

    Public Overrides Function btnDel_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Delete()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnDel_Click()
    End Function

    Public Overrides Function btnFirst_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_First()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnFirst_Click()
    End Function

    Public Overrides Function btnPrev_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Prev()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnPrev_Click()
    End Function

    Public Overrides Function btnNext_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Next()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnNext_Click()
    End Function

    Public Overrides Function btnLast_Click() As Boolean
        Me.Cursor = Cursors.WaitCursor
        Me.uiMstItemCluster_Last()
        Me.Cursor = Cursors.Arrow
        Return MyBase.btnLast_Click()
    End Function


#End Region

#Region " Layout & Init UI "

    Private Function FormatDgvMstItemCluster(ByRef objDgv As System.Windows.Forms.DataGridView) As Boolean
        ' Format DgvMstItemcategory Columns 
        Dim cGroup_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cGroup_name As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn

        cGroup_id.Name = "cluster_id"
        cGroup_id.HeaderText = "Cluster id"
        cGroup_id.DataPropertyName = "cluster_id"
        cGroup_id.Width = 125
        cGroup_id.Visible = True
        cGroup_id.ReadOnly = False

        cGroup_name.Name = "cluster_name"
        cGroup_name.HeaderText = "Cluster Name"
        cGroup_name.DataPropertyName = "cluster_name"
        cGroup_name.Width = 250
        cGroup_name.Visible = True
        cGroup_name.ReadOnly = False

        objDgv.Columns.Clear()
        objDgv.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() _
          {cGroup_id, cGroup_name})

        ' DgvMstItemcategory Behaviours: 
        objDgv.AllowUserToAddRows = False
        objDgv.AllowUserToDeleteRows = False
        objDgv.AllowUserToResizeRows = False
        objDgv.AutoGenerateColumns = False
        objDgv.ReadOnly = True
        objDgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect

    End Function

    Private Function FormatDgvMstItem(ByRef objDgv As System.Windows.Forms.DataGridView) As Boolean
        ' formating DgvMstItem
        Dim cItem_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cItem_name As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cItem_descr As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cCategory_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cIs_active As System.Windows.Forms.DataGridViewCheckBoxColumn = New System.Windows.Forms.DataGridViewCheckBoxColumn

        cItem_id.Name = "item_id"
        cItem_id.HeaderText = "Item ID"
        cItem_id.DataPropertyName = "item_id"
        cItem_id.Width = 125
        cItem_id.Visible = True
        cItem_id.ReadOnly = True

        cItem_name.Name = "item_name"
        cItem_name.HeaderText = "Item Name"
        cItem_name.DataPropertyName = "item_name"
        cItem_name.Width = 250
        cItem_name.Visible = True
        cItem_name.ReadOnly = False

        cItem_descr.Name = "cluster_id"
        cItem_descr.HeaderText = "Cluster ID"
        cItem_descr.DataPropertyName = "cluster_id"
        cItem_descr.Width = 350
        cItem_descr.Visible = True
        cItem_descr.ReadOnly = False

        'cCategory_id.Name = "category_id"
        'cCategory_id.HeaderText = "Category ID"
        'cCategory_id.DataPropertyName = "category_id"
        'cCategory_id.Width = 100
        'cCategory_id.Visible = False
        'cCategory_id.ReadOnly = False

        'cIs_active.Name = "is_active"
        'cIs_active.HeaderText = "Active"
        'cIs_active.DataPropertyName = "is_active"
        'cIs_active.Width = 60
        'cIs_active.Visible = False
        'cIs_active.ReadOnly = False

        objDgv.Columns.Clear()
        objDgv.AllowUserToAddRows = False
        objDgv.AllowUserToDeleteRows = False
        objDgv.AllowUserToResizeRows = False
        objDgv.AutoGenerateColumns = False
        objDgv.ReadOnly = False
        objDgv.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() _
        {cItem_id, cItem_name, cItem_descr}) ' cCategory_id, cIs_active})


    End Function

    Private Function FormatDgvMstItem_all(ByRef objDgv As System.Windows.Forms.DataGridView) As Boolean
        ' formating DgvMstItem_all
        Dim cItem_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cItem_name As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cCategory_id As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cItem_line As System.Windows.Forms.DataGridViewTextBoxColumn = New System.Windows.Forms.DataGridViewTextBoxColumn
        Dim cIs_active As System.Windows.Forms.DataGridViewCheckBoxColumn = New System.Windows.Forms.DataGridViewCheckBoxColumn

        cItem_id.Name = "item_id"
        cItem_id.HeaderText = "Item ID"
        cItem_id.DataPropertyName = "item_id"
        cItem_id.Width = 50
        cItem_id.Visible = False
        cItem_id.ReadOnly = False

        cItem_name.Name = "item_name"
        cItem_name.HeaderText = "Item Name"
        cItem_name.DataPropertyName = "item_name"
        cItem_name.Width = 200
        cItem_name.Visible = True
        cItem_name.ReadOnly = False

        cCategory_id.Name = "category_id"
        cCategory_id.HeaderText = "Category ID"
        cCategory_id.DataPropertyName = "category_id"
        cCategory_id.Width = 100
        cCategory_id.Visible = True
        cCategory_id.ReadOnly = False

        cItem_line.Name = "item_line"
        cItem_line.HeaderText = "Item Line"
        cItem_line.DataPropertyName = "item_line"
        cItem_line.Width = 100
        cItem_line.Visible = True
        cItem_line.ReadOnly = False

        cIs_active.Name = "is_active"
        cIs_active.HeaderText = "Active"
        cIs_active.DataPropertyName = "is_active"
        cIs_active.Width = 60
        cIs_active.Visible = True
        cIs_active.ReadOnly = False

        objDgv.Columns.Clear()
        objDgv.AutoGenerateColumns = False
        objDgv.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() _
        {cItem_id, cItem_name, cCategory_id, cItem_line, cIs_active})

        objDgv.AllowUserToAddRows = False
        objDgv.AllowUserToDeleteRows = False
        objDgv.AllowUserToResizeRows = False
        objDgv.AutoGenerateColumns = False
        objDgv.ReadOnly = True
        objDgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect

    End Function
    Private Function InitLayoutUI() As Boolean
        Me.ftabMain.Anchor = AnchorStyles.Bottom
        Me.ftabMain.Anchor += AnchorStyles.Top
        Me.ftabMain.Anchor += AnchorStyles.Right
        Me.ftabMain.Anchor += AnchorStyles.Left

        Me.ftabMain.TabPages.Item(1).BackColor = Color.Gainsboro
        Me.PnlDfSearch.Dock = DockStyle.Top
        Me.PnlDfSearch.Visible = False
        Me.PnlDfMain.Dock = DockStyle.Fill

        ' Me.PnlDfSearchItem.Dock = DockStyle.Top
        ' Me.PnlDfSearchItem.Visible = False
        Me.DgvMstItemCluster.Dock = DockStyle.Fill
        ' Me.DgvMstItem_All.Dock = DockStyle.Fill

        Me.FormatDgvMstItemCluster(Me.DgvMstItemClusterGroup)
        Me.FormatDgvMstItem(Me.DgvMstItemCluster)
        ' Me.FormatDgvMstItem_all(Me.DgvMstItem_All)

    End Function
    Private Function BindingStop() As Boolean
        'stop binding
        Me.obj_Group_id.DataBindings.Clear()
        Me.obj_Group_name.DataBindings.Clear()

        'Me.obj_Category_id.DataBindings.Clear()
        'Me.cbo_Category_name.DataBindings.Clear()

        Return True
    End Function
    Private Function BindingStart() As Boolean
        'start binding
        'Me.obj_Group_id.DataBindings.Add(New Binding("Text", Me.tbl_MstItemClusterGroup_Temp, "cluster_id"))
        'Me.obj_Group_name.DataBindings.Add(New Binding("Text", Me.tbl_MstItemClusterGroup_Temp, "cluster_name"))
        Me.obj_Group_id.DataBindings.Add(New Binding("Text", Me.tbl_MstItemClusterGroup_Temp, "cluster_id"))
        Me.obj_Group_name.DataBindings.Add(New Binding("Text", Me.tbl_MstItemClusterGroup_Temp, "cluster_name"))

        'Me.obj_Category_id.DataBindings.Add(New Binding("Text", Me.tbl_MstItemCluster, "category_id"))
        'Me.cbo_Category_name.DataBindings.Add(New Binding("Text", Me.tbl_MstItemCluster, "category_name"))

        Return True
    End Function


#End Region

#Region " Dialoged Control "
#End Region


#Region " User Defined Function "

    Private Function uiMstItemCluster_NewData() As Boolean
        'new data
        RaiseEvent FormBeforeNew()

        ' TODO: Set Default Value for tbl_MstItemCluster_Temp
        'Me.tbl_MstItemClusterGroup_Temp.Clear()

        ' TODO: Set Default Value for tbl_MstItem
        'Me.tbl_MstItem.Clear()
        'Me.tbl_MstItem = clsDataset.CreateTblMstItem()
        'Me.tbl_MstItem.Columns("category_id").DefaultValue = 0
        'Me.tbl_MstItem.Columns("item_line").DefaultValue = DBNull.Value
        'Me.tbl_MstItem.Columns("item_line").AutoIncrement = True
        'Me.tbl_MstItem.Columns("item_line").AutoIncrementSeed = 1
        'Me.tbl_MstItem.Columns("item_line").AutoIncrementStep = 1
        'Me.DgvMstItem.DataSource = Me.tbl_MstItem

        'Me.BindingContext(Me.tbl_MstItemClusterGroup_Temp).EndCurrentEdit()
        'Try
        '    Me.BindingContext(Me.tbl_MstItemClusterGroup_Temp).AddNew()
        'Catch ex As Exception
        '    MessageBox.Show(ex.Source)
        'End Try

    End Function

    Private Function uiMstItemCluster_Retrieve() As Boolean
        'retrieve data
        Dim criteria As String = ""

        ' TODO: Parse Criteria using clsProc.RefParser()

        Me.tbl_MstItemClusterGroup.Clear()
        Try
            Me.DataFill(Me.tbl_MstItemClusterGroup, "pr_MstItemClustergroup_Select", criteria)
            Me.tbl_MstItemClusterGroup.DefaultView.Sort = "cluster_id"
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

        Me.tbl_temp.Clear()
        Try
            Me.DataFill(Me.tbl_temp, "pr_MstItemCluster_Select", criteria)
            'Dim category_id As String = Me.tbl_MstItemCluster.Rows(0)("category_id").ToString
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
       
        Me.tbl_MstItem_all.Clear()
        Try
            Me.DataFill(Me.tbl_MstItem_all, "pr_MstItem_Select", criteria)
            Me.tbl_MstItem_all.DefaultView.Sort = "item_name"
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Function

    Private Function uiMstItemCluster_Save() As Boolean
        'save data
        Dim tbl_MstItem_Changes As DataTable
        Dim success As Boolean
        Dim item_id As Object = New Object
        Dim i As Integer = 0
        Dim MasterDataState As System.Data.DataRowState
        Dim result As FormSaveResult

        Me.Cursor = Cursors.WaitCursor
        'RaiseEvent FormBeforeSave(item_id)

        Me.BindingContext(Me.tbl_MstItemCluster_temp).EndCurrentEdit()

        Me.DgvMstItemCluster.EndEdit()
        Me.BindingContext(Me.tbl_MstItemCluster).EndCurrentEdit()
        tbl_MstItem_Changes = Me.tbl_MstItemCluster.GetChanges()

        If tbl_MstItem_Changes IsNot Nothing Then

            'cluster_id = Me.obj_Group_id.Text.ToString
            ' If category_id = "" Then
            'MsgBox("Please select category first..", MsgBoxStyle.Information, "Category not selected")
            ' Else
            Try
                ' item_id.ToString()
                If tbl_MstItem_Changes IsNot Nothing Then
                    For i = 0 To Me.tbl_MstItemCluster.Rows.Count - 1
                        If Me.tbl_MstItemCluster.Rows(i).RowState = DataRowState.Added Then
                            item_id = Me.tbl_MstItemCluster.Rows(i).Item("item_id")
                           
                        End If
                        success = Me.uiMstItemCluster_SaveDetil(item_id, tbl_MstItem_Changes, MasterDataState)
                        If Not success Then Throw New Exception("Error: Save Detil Data at Me.uiMstItemCluster_SaveDetil(tbl_MstItem_Changes)")
                    Next

                    Me.tbl_MstItem.AcceptChanges()
                End If

                result = FormSaveResult.SaveSuccess
                If SHOW_SAVE_CONFIRMATION Then
                    MessageBox.Show("Data Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
                End If

            Catch ex As Exception
                result = FormSaveResult.SaveError
                MessageBox.Show("Data Cannot Be Saved" & vbCrLf & ex.Message, mUiName, MessageBoxButtons.OK, MessageBoxIcon.Error)
            End Try
            'End If
        Else
            result = FormSaveResult.Nochanges
            If SHOW_SAVE_CONFIRMATION Then
                MessageBox.Show("All changes has been saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
            End If
        End If

        RaiseEvent FormAfterSave(item_id, result)
        Me.Cursor = Cursors.Arrow

    End Function

    Private Function uiMstItemCluster_SaveMaster(ByRef category_id As Object, ByVal objTbl As DataTable, ByVal MasterDataState As System.Data.DataRowState) As Boolean
        'Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        'Dim dbCmdInsert As OleDb.OleDbCommand
        'Dim dbCmdUpdate As OleDb.OleDbCommand
        'Dim dbDA As OleDb.OleDbDataAdapter
        'Dim curpos As Integer

        '' Save data: master_Itemcategory
        'dbCmdInsert = New OleDb.OleDbCommand("pr_MstItemcategory_Insert", dbConn)
        'dbCmdInsert.CommandType = CommandType.StoredProcedure
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_id", System.Data.OleDb.OleDbType.VarWChar, 30, "category_id"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_name", System.Data.OleDb.OleDbType.VarWChar, 60, "category_name"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_code", System.Data.OleDb.OleDbType.VarWChar, 4, "category_code"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_spktype", System.Data.OleDb.OleDbType.VarWChar, 100, "category_spktype"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@is_spk", System.Data.OleDb.OleDbType.Boolean, 1, "is_spk"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@cat_id", System.Data.OleDb.OleDbType.Integer, 4, "cat_id"))


        'dbCmdUpdate = New OleDb.OleDbCommand("pr_MstItemcategory_Update", dbConn)
        'dbCmdUpdate.CommandType = CommandType.StoredProcedure
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_id", System.Data.OleDb.OleDbType.VarWChar, 30, "category_id"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_name", System.Data.OleDb.OleDbType.VarWChar, 60, "category_name"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_code", System.Data.OleDb.OleDbType.VarWChar, 4, "category_code"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_spktype", System.Data.OleDb.OleDbType.VarWChar, 100, "category_spktype"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@is_spk", System.Data.OleDb.OleDbType.Boolean, 1, "is_spk"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@cat_id", System.Data.OleDb.OleDbType.Integer, 4, "cat_id"))


        'dbDA = New OleDb.OleDbDataAdapter
        'dbDA.UpdateCommand = dbCmdUpdate
        'dbDA.InsertCommand = dbCmdInsert


        'dbDA = New OleDb.OleDbDataAdapter
        'dbDA.UpdateCommand = dbCmdUpdate
        'dbDA.InsertCommand = dbCmdInsert


        'Try
        '    dbConn.Open()
        '    dbDA.Update(objTbl)

        '    category_id = objTbl.Rows(0).Item("category_id")
        '    Me.tbl_MstItemClusterGroup_Temp.Clear()
        '    Me.tbl_MstItemClusterGroup_Temp.Merge(objTbl)

        'Catch ex As Data.OleDb.OleDbException
        '    MessageBox.Show(ex.Message, "OLE DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
        '    Return False
        'Catch ex As Exception
        '    MessageBox.Show(ex.Message)
        '    Return False
        'Finally
        '    dbConn.Close()
        'End Try


        'If MasterDataState = DataRowState.Added Then
        '    Me.tbl_MstItemCluster.Merge(objTbl)
        'ElseIf MasterDataState = DataRowState.Modified Then
        '    curpos = Me.BindingContext(Me.tbl_MstItemCluster).Position
        '    Me.tbl_MstItemCluster.Rows.RemoveAt(curpos)
        '    Me.tbl_MstItemCluster.Merge(objTbl)
        'End If

        'Me.BindingContextMe.tbl_MstItemCluster).Position = Me.BindingContext(Me.tbl_MstItemCluster).Count

        Return True
    End Function

    Private Function uiMstItemCluster_SaveDetil(ByRef item_id As Object, ByVal objTbl As DataTable, ByVal MasterDataState As System.Data.DataRowState) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        Dim dbCmdInsert As OleDb.OleDbCommand
        Dim dbCmdUpdate As OleDb.OleDbCommand
        'Dim dbCmdDelete As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter

        ' Save data: master_Item
        dbCmdInsert = New OleDb.OleDbCommand("pr_MstItemCluster_Insert", dbConn)
        dbCmdInsert.CommandType = CommandType.StoredProcedure
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_id", System.Data.OleDb.OleDbType.VarWChar, 30, "item_id"))
        dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@cluster_id", System.Data.OleDb.OleDbType.VarWChar, 30, "cluster_id"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_descr", System.Data.OleDb.OleDbType.VarWChar, 510, "item_descr"))
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_id", System.Data.OleDb.OleDbType.VarWChar, 30))
        ' dbCmdInsert.Parameters("@item_id").Value = item_id
        'dbCmdInsert.Parameters.Add(New System.Data.OleDb.OleDbParameter("@is_active", System.Data.OleDb.OleDbType.Boolean, 1, "is_active"))


        dbCmdUpdate = New OleDb.OleDbCommand("pr_MstItemCluster_Update", dbConn)
        dbCmdUpdate.CommandType = CommandType.StoredProcedure
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_id", System.Data.OleDb.OleDbType.VarWChar, 30, "item_id"))
        dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@cluster_id", System.Data.OleDb.OleDbType.VarWChar, 30, "cluster_id"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_descr", System.Data.OleDb.OleDbType.VarWChar, 510, "item_descr"))
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_id", System.Data.OleDb.OleDbType.VarWChar, 30))
        ' dbCmdUpdate.Parameters("@item_id").Value = item_id
        'dbCmdUpdate.Parameters.Add(New System.Data.OleDb.OleDbParameter("@is_active", System.Data.OleDb.OleDbType.Boolean, 1, "is_active"))


        'dbCmdDelete = New OleDb.OleDbCommand("pr_MstItem_Delete", dbConn)
        'dbCmdDelete.CommandType = CommandType.StoredProcedure
        'dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_id", System.Data.OleDb.OleDbType.VarWChar, 30, "item_id"))
        'dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_name", System.Data.OleDb.OleDbType.VarWChar, 200, "item_name"))
        'dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_descr", System.Data.OleDb.OleDbType.VarWChar, 510, "item_descr"))
        'dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@category_id", System.Data.OleDb.OleDbType.VarWChar, 30))
        'dbCmdDelete.Parameters("@category_id").Value = category_id
        'dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@is_active", System.Data.OleDb.OleDbType.Boolean, 1, "is_active"))


        dbDA = New OleDb.OleDbDataAdapter
        dbDA.UpdateCommand = dbCmdUpdate
        dbDA.InsertCommand = dbCmdInsert
        'dbDA.DeleteCommand = dbCmdDelete


        Try
            dbConn.Open()
            dbDA.Update(objTbl)

        Catch ex As Data.OleDb.OleDbException
            MessageBox.Show(ex.Message, "OLE DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
            Return False
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Return False
        Finally
            dbConn.Close()
        End Try

        Return True
    End Function

    Private Function uiMstItemCluster_Print() As Boolean
        'print data
    End Function

    Private Function uiMstItemCluster_Delete() As Boolean
      
    End Function

    Private Function uiMstItemCluster_DeleteRow(ByVal rowIndex As Integer) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        Dim dbCmdDelete As OleDb.OleDbCommand
        Dim item_id As String
        Dim NewRowIndex As Integer

        item_id = Me.DgvMstItemCluster.Rows(rowIndex).Cells("item_id").Value

        dbCmdDelete = New OleDb.OleDbCommand("pr_MstItemCluster_Delete", dbConn)
        dbCmdDelete.CommandType = CommandType.StoredProcedure
        dbCmdDelete.Parameters.Add(New System.Data.OleDb.OleDbParameter("@item_id", System.Data.OleDb.OleDbType.VarWChar, 30))
        dbCmdDelete.Parameters("@item_id").Value = item_id

        Try
            dbConn.Open()
            dbCmdDelete.ExecuteNonQuery()
            If Me.DgvMstItemCluster.Rows.Count > 1 Then
                If rowIndex = 0 Then
                    NewRowIndex = rowIndex + 1
                    Me.uiMstItemCluster_OpenRow(NewRowIndex)
                    Me.tbl_MstItemCluster.Rows.RemoveAt(rowIndex)
                ElseIf rowIndex = Me.DgvMstItemCluster.Rows.Count - 1 Then
                    NewRowIndex = rowIndex - 1
                    Me.uiMstItemCluster_OpenRow(NewRowIndex)
                    Me.tbl_MstItemCluster.Rows.RemoveAt(rowIndex)
                Else
                    Me.tbl_MstItemCluster.Rows.RemoveAt(rowIndex)
                    Me.uiMstItemCluster_OpenRow(rowIndex)
                End If
            Else
                Me.tbl_MstItemCluster_temp.Clear()
                Me.tbl_MstItemCluster.Rows.RemoveAt(rowIndex)
            End If
        Catch ex As Data.OleDb.OleDbException
            MessageBox.Show(ex.Message, "OLE DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error)
            Exit Function
        Catch ex As Exception
            MessageBox.Show(ex.Message)
            Exit Function
        Finally
            dbConn.Close()
        End Try
    End Function

    Private Function uiMstItemCluster_OpenRow(ByVal rowIndex As Integer) As Boolean
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        Dim cluster_id As String

        cluster_id = Me.DgvMstItemClusterGroup.Rows(rowIndex).Cells("cluster_id").Value

        Me.Cursor = Cursors.WaitCursor
        RaiseEvent FormBeforeOpenRow(cluster_id)

        Try
            dbConn.Open()
            Me.uiMstItemCluster_OpenRowGroup(cluster_id, dbConn)
            Me.uiMstItemCluster_OpenRowCategory(cluster_id, dbConn)

        Catch ex As Exception
            MessageBox.Show(ex.Message, mUiName & ": uiMstItemCluster_OpenRow()", MessageBoxButtons.OK, MessageBoxIcon.Error)
        Finally
            dbConn.Close()
        End Try

        RaiseEvent FormAfterOpenRow(cluster_id)
        Me.Cursor = Cursors.Arrow

        Return True

    End Function

    Private Function uiMstItemCluster_OpenRowGroup(ByVal cluster_id As String, ByVal dbConn As OleDb.OleDbConnection) As Boolean
        Dim dbCmd As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter

        dbCmd = New OleDb.OleDbCommand("pr_MstItemClustergroup_Select", dbConn)
        dbCmd.Parameters.Add("@Criteria", Data.OleDb.OleDbType.VarChar)
        dbCmd.Parameters("@Criteria").Value = String.Format("cluster_id='{0}'", cluster_id)
        dbCmd.CommandType = CommandType.StoredProcedure
        dbDA = New OleDb.OleDbDataAdapter(dbCmd)

        Me.tbl_MstItemClusterGroup_Temp.Clear()

        Try
            Me.BindingStop()
            dbDA.Fill(Me.tbl_MstItemClusterGroup_Temp)
            Me.BindingStart()
        Catch ex As Exception
            Throw New Exception(mUiName & ": uiMstItemCluster_OpenRowGroup()" & vbCrLf & ex.Message)
        End Try

    End Function

    'Private Function uiMstItemCluster_OpenRowCategory(ByVal cluster_id As String, ByVal dbConn As OleDb.OleDbConnection) As Boolean
    '    'Dim criteria As String = "group_id = '" & group_id & "'"
    '    Dim criteria As String = "master_itemclusterdetail.cluster_id= '" & cluster_id & "'"

    '    Me.tbl_MstItemCluster.Clear()
    '    Try
    '        Me.ComboFill(Me.cbo_Category_name, "item_id", "item_name", Me.tbl_MstItemCluster, "pr_MstItemCluster_Select", criteria)
    '        Me.tbl_MstItemCluster.DefaultView.Sort = "item_name"
    '    Catch ex As Exception
    '        Throw New Exception(mUiName & ": uiMstItemCluster_OpenRowCategory()" & vbCrLf & ex.Message)
    '    End Try

    'End Function
    Private Function uiMstItemCluster_OpenRowCategory(ByVal cluster_id As String, ByVal dbConn As OleDb.OleDbConnection) As Boolean
        Dim dbCmd As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter

        dbCmd = New OleDb.OleDbCommand("pr_MstItemCluster_Select", dbConn)
        dbCmd.Parameters.Add("@Criteria", Data.OleDb.OleDbType.VarChar)
        dbCmd.Parameters("@Criteria").Value = String.Format("master_itemclusterdetail.cluster_id='{0}'", cluster_id)
        dbCmd.CommandType = CommandType.StoredProcedure
        dbDA = New OleDb.OleDbDataAdapter(dbCmd)

        Me.tbl_MstItemCluster.Clear()

        Try
            Me.BindingStop()
            dbDA.Fill(Me.tbl_MstItemCluster)
            Me.BindingStart()
        Catch ex As Exception
            Throw New Exception(mUiName & ": uiMstItemCluster_OpenRowCategory()" & vbCrLf & ex.Message)
        End Try

    End Function

    Private Function uiMstItemCluster_OpenRowItem(ByVal item_id As String, ByVal dbConn As OleDb.OleDbConnection) As Boolean
        Dim dbCmd As OleDb.OleDbCommand
        Dim dbDA As OleDb.OleDbDataAdapter

        dbCmd = New OleDb.OleDbCommand("pr_MstItemCluster_Select", dbConn)
        dbCmd.Parameters.Add("@Criteria", Data.OleDb.OleDbType.VarChar)
        dbCmd.Parameters("@Criteria").Value = String.Format("master_itemclusterdetail.item_id='{0}'", item_id)
        dbCmd.CommandType = CommandType.StoredProcedure
        dbDA = New OleDb.OleDbDataAdapter(dbCmd)

        Me.tbl_MstItem.Clear()

        Try
            'Me.BindingStop()
            dbDA.Fill(Me.tbl_MstItem)
            Me.tbl_MstItem.DefaultView.Sort = "item_name"
            'Me.BindingStart()
        Catch ex As Exception
            Throw New Exception(mUiName & ": uiMstItemCluster_OpenRowItem()" & vbCrLf & ex.Message)
        End Try

    End Function

    Private Function uiMstItemCluster_First() As Boolean
        'goto first record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to first record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstItemCluster_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            Me.DgvMstItemClusterGroup.CurrentCell = Me.DgvMstItemClusterGroup(1, 0)
            Me.uiMstItemCluster_RefreshPosition()
        End If
    End Function

    Private Function uiMstItemCluster_Prev() As Boolean
        'goto previous record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to previous record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstItemCluster_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            If Me.DgvMstItemClusterGroup.CurrentCell.RowIndex > 0 Then
                Me.DgvMstItemClusterGroup.CurrentCell = Me.DgvMstItemClusterGroup(1, DgvMstItemClusterGroup.CurrentCell.RowIndex - 1)
                Me.uiMstItemCluster_RefreshPosition()
            End If
        End If
    End Function

    Private Function uiMstItemCluster_Next() As Boolean
        'goto next record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to next record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstItemCluster_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            If Me.DgvMstItemClusterGroup.CurrentCell.RowIndex < Me.DgvMstItemClusterGroup.Rows.Count - 1 Then
                Me.DgvMstItemClusterGroup.CurrentCell = Me.DgvMstItemClusterGroup(1, DgvMstItemClusterGroup.CurrentCell.RowIndex + 1)
                Me.uiMstItemCluster_RefreshPosition()
            End If
        End If
    End Function

    Private Function uiMstItemCluster_Last() As Boolean
        'goto last record found
        Dim move As Boolean
        Dim Message As String = "Data has been changed. " & vbCrLf & "Save data changes before move to next record ?"
        Dim iTab As Integer = Me.ftabMain.SelectedIndex

        If iTab = 1 Then
            If Me.DATA_ISLOCKED Then
                move = True
            Else
                move = Me.uiMstItemCluster_ConfirmSaveBeforeMove(Message)
            End If
        Else
            move = True
        End If

        If move Then
            Me.DgvMstItemClusterGroup.CurrentCell = Me.DgvMstItemClusterGroup(1, Me.DgvMstItemClusterGroup.Rows.Count - 1)
            Me.uiMstItemCluster_RefreshPosition()
        End If
    End Function

    Private Function uiMstItemCluster_RefreshPosition() As Boolean
        'refresh position
        Dim iTab As Integer = Me.ftabMain.SelectedIndex
        If iTab = 1 Then uiMstItemCluster_OpenRow(Me.DgvMstItemClusterGroup.CurrentRow.Index)
    End Function

    Private Function uiMstItemCluster_ConfirmSaveBeforeMove(ByVal Message As String) As Boolean
        'confirm saving data changes before move
        Dim tbl_MstItemCluster_Temp_Changes As DataTable
        Dim tbl_MstItem_Changes As DataTable
        Dim res As System.Windows.Forms.DialogResult
        Dim success As Boolean
        Dim i As Integer = 0
        Dim MasterDataState As System.Data.DataRowState
        Dim category_id As Object = New Object
        Dim move As Boolean = False
        Dim result As FormSaveResult


        If Me.DgvMstItemClusterGroup.CurrentCell IsNot Nothing Then

            Me.BindingContext(Me.tbl_MstItemClusterGroup_Temp).EndCurrentEdit()
            tbl_MstItemCluster_Temp_Changes = Me.tbl_MstItemClusterGroup_Temp.GetChanges()

            Me.DgvMstItemCluster.EndEdit()
            Me.BindingContext(Me.tbl_MstItem).EndCurrentEdit()
            tbl_MstItem_Changes = Me.tbl_MstItem.GetChanges()

            If tbl_MstItemCluster_Temp_Changes IsNot Nothing Or tbl_MstItem_Changes IsNot Nothing Then

                res = MessageBox.Show(Message, mUiName, MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question)
                Select Case res
                    Case DialogResult.Yes

                        RaiseEvent FormBeforeSave(category_id)

                        Try

                            If tbl_MstItemCluster_Temp_Changes IsNot Nothing Then
                                success = Me.uiMstItemCluster_SaveMaster(category_id, tbl_MstItemCluster_Temp_Changes, MasterDataState)
                                If Not success Then Throw New Exception("Cannot Save Master Data")
                                Me.tbl_MstItemClusterGroup_Temp.AcceptChanges()
                            End If

                            If tbl_MstItem_Changes IsNot Nothing Then
                                For i = 0 To Me.tbl_MstItem.Rows.Count - 1
                                    If Me.tbl_MstItem.Rows(i).RowState = DataRowState.Added Then
                                        Me.tbl_MstItem.Rows(i).Item("category_id") = category_id
                                    End If
                                Next
                                success = Me.uiMstItemCluster_SaveDetil(category_id, tbl_MstItem_Changes, MasterDataState)
                                If Not success Then Throw New Exception("Cannot Save Detil Data")
                                Me.tbl_MstItem.AcceptChanges()
                            End If

                            result = FormSaveResult.SaveSuccess
                            If SHOW_SAVE_CONFIRMATION Then
                                MessageBox.Show("Data Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Information)
                            End If

                        Catch ex As Exception
                            result = FormSaveResult.SaveError
                            MessageBox.Show(ex.Message & vbCrLf & "Data Cannot Be Saved", mUiName, MessageBoxButtons.OK, MessageBoxIcon.Error)
                        End Try

                        RaiseEvent FormAfterSave(category_id, result)

                    Case DialogResult.No
                        move = True
                    Case DialogResult.Cancel
                        move = False
                End Select
            Else
                move = True
            End If

        End If

        Return move

    End Function

    Private Function uiMstItemCluster_FormError() As Boolean
        Try
            ' TODO: Cek Error disini
            ' objFormError.SetError()

            ' Throw New Exception("Error")
        Catch ex As Exception
            MessageBox.Show(ex.Message, mUiName, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
            Return True
        End Try
        Return False
    End Function

#End Region



    Private Sub uiMstItemCluster_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

        Dim objParameters As Collection = New Collection


        'TODO: - Extract Parameter
        '      - Assign parameter
        If Me.Browser IsNot Nothing Then
            objParameters = Me.GetParameterCollection(Me.Parameter)
        End If

        Me.InitLayoutUI()

        Me.DgvMstItemClusterGroup.DataSource = Me.tbl_MstItemClusterGroup
        ' Me.DgvMstItem_All.DataSource = Me.tbl_MstItem_all
        Me.DgvMstItemCluster.DataSource = Me.tbl_MstItemCluster

        Me.BindingStop()
        Me.BindingStart()

        Me.uiMstItemCluster_NewData()

        Me.tbtnDel.Enabled = False
        Me.tbtnEdit.Enabled = False
        Me.tbtnFirst.Enabled = False
        Me.tbtnPrev.Enabled = False
        Me.tbtnNext.Enabled = False
        Me.tbtnLast.Enabled = False
        Me.tbtnNew.Enabled = False
        Me.tbtnQuery.Enabled = False
        Me.tbtnRefresh.Enabled = False
        Me.tbtnSave.Enabled = False
        Me.tbtnPrint.Enabled = False
        Me.tbtnPrintPreview.Enabled = False


    End Sub

    Private Sub ftabMain_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs) Handles ftabMain.SelectedIndexChanged

        Select Case ftabMain.SelectedIndex
            Case 0
                Me.tbtnSave.Enabled = False
                Me.tbtnDel.Enabled = False
                Me.tbtnLoad.Enabled = True
                Me.tbtnQuery.Enabled = False
                Me.tbtnFirst.Enabled = True
                Me.tbtnLast.Enabled = True
                Me.tbtnNext.Enabled = True
                Me.tbtnPrev.Enabled = True
                Me.ftabMain.TabPages.Item(0).BackColor = Color.White
                Me.ftabMain.TabPages.Item(1).BackColor = Color.Gainsboro
                'Me.ftabMain.TabPages.Item(2).BackColor = Color.Gainsboro

            Case 1
                Me.tbtnSave.Enabled = True
                Me.tbtnDel.Enabled = False
                Me.tbtnLoad.Enabled = False
                Me.tbtnQuery.Enabled = False
                Me.tbtnFirst.Enabled = True
                Me.tbtnLast.Enabled = True
                Me.tbtnNext.Enabled = True
                Me.tbtnPrev.Enabled = True
                Me.ftabMain.TabPages.Item(0).BackColor = Color.Gainsboro
                Me.ftabMain.TabPages.Item(1).BackColor = Color.White
                ' Me.ftabMain.TabPages.Item(2).BackColor = Color.Gainsboro

                If Me.DgvMstItemClusterGroup.CurrentRow IsNot Nothing Then
                    Me.uiMstItemCluster_OpenRow(Me.DgvMstItemClusterGroup.CurrentRow.Index)
                Else
                    Me.uiMstItemCluster_NewData()
                End If

            Case 2
                Me.tbtnSave.Enabled = False
                Me.tbtnDel.Enabled = False
                Me.tbtnLoad.Enabled = False
                Me.tbtnQuery.Enabled = False
                Me.tbtnFirst.Enabled = False
                Me.tbtnLast.Enabled = False
                Me.tbtnNext.Enabled = False
                Me.tbtnPrev.Enabled = False
                Me.tbtnPrintPreview.Enabled = False
                Me.tbtnRefresh.Enabled = False
                Me.ftabMain.TabPages.Item(0).BackColor = Color.Gainsboro
                Me.ftabMain.TabPages.Item(1).BackColor = Color.Gainsboro
                ' Me.ftabMain.TabPages.Item(2).BackColor = Color.White

        End Select

    End Sub

    Private Sub DgvMstItemCategoryGroup_CellDoubleClick(ByVal sender As System.Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs) Handles DgvMstItemClusterGroup.CellDoubleClick
        If e.ColumnIndex < 0 Or e.RowIndex < 0 Then
            Exit Sub
        End If
        If Me.DgvMstItemClusterGroup.CurrentRow IsNot Nothing Then
            Me.ftabMain.SelectedIndex = 1
        End If
    End Sub

    Private Sub cbo_Category_name_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cbo_Category_name.SelectedIndexChanged
        Dim dbConn As OleDb.OleDbConnection = New OleDb.OleDbConnection(Me.DSN)
        Dim item_id As String

        If Me.cbo_Category_name.SelectedIndex > 0 Then
            item_id = Me.cbo_Category_name.SelectedValue
            Me.obj_Category_id.Text = item_id
            Me.uiMstItemCluster_OpenRowItem(item_id, dbConn)
        Else
            Me.obj_Category_id.Text = ""
            Me.tbl_MstItem.Clear()
        End If



    End Sub

    Private Sub btnAddItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnAddItem.Click
        Dim criteria As String
        Dim criteria_2 As String = ""
        Dim retRow() As DataRow

        Dim txtSearchCriteria As String = ""
        Dim txtCondition As String = ""

        Dim newRow As DataRow
        Dim rowIndex, colIndex
        Dim colName As String

        'Me.tbl_temp.Clear()
        'Try
        '    Me.DataFill(Me.tbl_temp, "pr_MstItemCluster2_Select", criteria_2)
        '    'Dim category_id As String = Me.tbl_MstItemCluster.Rows(0)("category_id").ToString
        'Catch ex As Exception
        '    MsgBox(ex.Message)
        'End Try

        'For i = 0 To Me.tbl_temp.Rows.Count - 1
        '    txtSearchCriteria = String.Format(" master_item.item_id <>  '{0}' ", Me.tbl_temp.Rows(i).Item("item_id"))
        '    If txtCondition = "" Then
        '        txtCondition = txtSearchCriteria
        '    Else
        '        txtCondition = txtCondition & " AND " & txtSearchCriteria
        '    End If

        'Next
        criteria = txtCondition
        Dim dlg As New dlgSelectItem(Me.DSN, criteria)
        'Me.tbl_MstItem_all_temp.Clear()
        'Try
        'Me.DataFill(Me.tbl_MstItem_all_temp, "pr_MstItem_Select", criteria)
        '    Me.tbl_MstItem_all.DefaultView.Sort = "item_name"
        'Catch ex As Exception
        '    MsgBox(ex.Message)
        'End Try

        'request_id = Me.DgvTrnRequest.Rows(rowIndex).Cells("request_id").Value

        retRow = dlg.OpenDialog(Me)

        If retRow IsNot Nothing Then
            For rowIndex = 0 To retRow.GetUpperBound(0)
                newRow = Me.tbl_MstItemCluster.NewRow
                For colIndex = 0 To Me.tbl_MstItemCluster.Columns.Count - 1
                    colName = Me.tbl_MstItemCluster.Columns(colIndex).ColumnName
                    Select Case colName
                        Case "item_id"
                            newRow(colName) = retRow(rowIndex).Item("item_id")
                        Case "item_name"
                            newRow(colName) = retRow(rowIndex).Item("item_name")
                        Case "cluster_id"
                            newRow(colName) = Me.obj_Group_id.Text
                    End Select
                Next
                Me.tbl_MstItemCluster.Rows.Add(newRow)
            Next

    
        End If
    End Sub

    Private Sub btnDelItem_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnDelItem.Click
        Dim res As String = ""
        Dim item_id As Object = New Object

        Me.Cursor = Cursors.WaitCursor
        RaiseEvent FormBeforeDelete(item_id)

        Me.Cursor = Cursors.WaitCursor
        If Me.DgvMstItemCluster.CurrentRow IsNot Nothing Then

            res = MessageBox.Show("Are you sure want to delete data ?", mUiName, MessageBoxButtons.YesNo, MessageBoxIcon.Question)
            If res = DialogResult.Yes Then
                Me.uiMstItemCluster_DeleteRow(Me.DgvMstItemCluster.CurrentRow.Index)
            End If

        End If

        RaiseEvent FormAfterDelete(item_id)
        Me.Cursor = Cursors.Arrow
    End Sub
End Class
